name: Deploy

on:
  workflow_dispatch:
    inputs:
      val:
        description: "Returned value"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout️
        uses: actions/checkout@v4
#        TODO: npm install
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1 # TODO: infer the region from SST config
          role-to-assume: arn:aws:iam::965517595227:role/prod-ga-test-aws-deployme-githubactionaccessCDE4795-oizFu9z2ggAi # TODO: infer from the SST outputs
          audience: ${{ github.triggering_actor }}
      - name: Deploy
        run: |
          npx sst deploy --stage prod
        env:
          MOCK_VALUE: ${{ inputs.val }}