name: Deploy

on:
  workflow_dispatch:
    inputs:
      val:
        description: "Returned value"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout️
        uses: actions/checkout@v2
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1 # TODO: infer the region from SST config
      - name: Deploy
        run: |
          npx sst deploy --stage prod
        env:
          MOCK_VALUE: ${{ inputs.val }}